export const products = [
  {
    id: 1,
    name: "SonicPro Wireless Headphones",
    price: 249.99,
    originalPrice: 299.99,
    discount: 16,
    image: "/wireless_headphone_1776096124687.png",
    category: "Audio",
    description: "Experience silence with premium active noise cancelling. Over-ear comfort designed for long studio sessions.",
    rating: 4.8,
    reviews: 124,
    specs: ["Active Noise Cancelling", "40-hour Battery Life", "Bluetooth 5.3", "Over-Ear Design"]
  },
  {
    id: 2,
    name: "Aura Mechanical Keyboard",
    price: 159.99,
    originalPrice: 159.99,
    discount: 0,
    image: "/mechanical_keyboard_1776096147193.png",
    category: "Accessories",
    description: "Tactile switches with customizable per-key RGB lighting. Built with aircraft-grade aluminum frame.",
    rating: 4.9,
    reviews: 89,
    specs: ["Cherry MX Brown Switches", "Per-key RGB", "Aluminum Frame", "Wireless/Wired mode"]
  },
  {
    id: 3,
    name: "Nexus Smartwatch Series X",
    price: 299.99,
    originalPrice: 349.99,
    discount: 14,
    image: "/smartwatch_1776096167288.png",
    category: "Wearables",
    description: "Advanced health tracking with an AMOLED edge-to-edge display. Stay connected without picking up your phone.",
    rating: 4.7,
    reviews: 210,
    specs: ["AMOLED Display", "ECG Monitor", "Water Resistant 50m", "Always-on Display"]
  },
  {
    id: 4,
    name: "AeroBlade Pro Laptop",
    price: 1699.99,
    originalPrice: 1899.99,
    discount: 10,
    image: "/laptop_1776097231661.png",
    category: "Computers",
    description: "High-performance laptop featuring a sleek aluminum body, 14-core processor, and dedicated graphics. Built for power users and creators.",
    rating: 4.9,
    reviews: 345,
    specs: ["14-core Processor", "32GB RAM", "1TB Gen4 NVMe", "16-inch Mini-LED 120Hz"]
  },
  {
    id: 5,
    name: "Zenith X1 Smartphone",
    price: 999.99,
    originalPrice: 999.99,
    discount: 0,
    image: "/smartphone_1776097249672.png",
    category: "Mobiles",
    description: "Flagship mobile experience. Edge-to-edge 6.8\" screen, pro-grade triple camera array, and blazing fast 5G speeds.",
    rating: 4.6,
    reviews: 1420,
    specs: ["6.8\" OLED 144Hz", "108MP Main Camera", "5000mAh Battery", "Snapdragon Elite Gen"]
  },
  {
    id: 6,
    name: "Lumix Alpha Mirrorless",
    price: 2199.00,
    originalPrice: 2499.00,
    discount: 12,
    image: "/camera_1776097270057.png",
    category: "Cameras",
    description: "Capture the world in stunning detail. Professional mirrorless full-frame camera engineered for cinematic video and high-res photography.",
    rating: 4.9,
    reviews: 55,
    specs: ["Full-Frame Sensor", "8K Video Recording", "In-body Stabilization", "Dual SD Slots"]
  },
  {
    id: 7,
    name: "Silk Flow Evening Dress",
    price: 129.50,
    originalPrice: 150.00,
    discount: 14,
    image: "/fashion_dress_1776609099633.png",
    category: "Fashion",
    description: "Elegant silk dress for special occasions. Features a breathable fabric and a sophisticated floral pattern.",
    rating: 4.7,
    reviews: 42,
    specs: ["100% Silk", "Floral Pattern", "Breathable", "Evening Wear"]
  },
  {
    id: 8,
    name: "Premium Organic Pantry Bundle",
    price: 45.00,
    originalPrice: 60.00,
    discount: 25,
    image: "/grocery_items_1776609119946.png",
    category: "Grocery",
    description: "A curated selection of premium organic pantry staples including cold-pressed olive oil and artisan pasta.",
    rating: 4.9,
    reviews: 215,
    specs: ["Organic Certified", "Artisan Quality", "Eco-friendly Packaging"]
  },
  {
    id: 9,
    name: "Executive Stationery Set",
    price: 85.00,
    originalPrice: 85.00,
    discount: 0,
    image: "/stationery_set_1776609141775.png",
    category: "Stationery",
    description: "Complete set for the modern professional. Includes a leather-bound journal and a gold-plated fountain pen.",
    rating: 4.8,
    reviews: 67,
    specs: ["Leather Bound", "Gold-Plated Pen", "Acid-free Paper"]
  },
  {
    id: 11,
    name: "Aura UltraWide Gaming Monitor",
    price: 799.99,
    originalPrice: 899.99,
    discount: 11,
    image: "/gaming_monitor_1776680701805.png",
    category: "Monitors",
    description: "Immersive 34-inch curved display with 175Hz refresh rate and HDR400. Perfect for elite gaming and cinematic experiences.",
    rating: 4.9,
    reviews: 156,
    specs: ["34\" QHD OLED", "175Hz Refresh", "0.03ms GTG", "HDR400 True Black"]
  },
  {
    id: 12,
    name: "Horizon Cinema Soundbar",
    price: 449.99,
    originalPrice: 499.99,
    discount: 10,
    image: "/soundbar_audio_1776680765433.png",
    category: "Audio",
    description: "Full-spectrum audio with integrated subwoofer and Dolby Atmos support. Transform your living room into a theater.",
    rating: 4.7,
    reviews: 82,
    specs: ["Dolby Atmos", "300W Output", "Bluetooth 5.2", "HDMI eARC"]
  },
  {
    id: 13,
    name: "Nexus Smart Hub Pro",
    price: 129.00,
    originalPrice: 129.00,
    discount: 0,
    image: "/smart_home_hub_1776680728147.png",
    category: "Accessories",
    description: "The brain of your smart home. Control lighting, temperature, and security with an intuitive touch interface.",
    rating: 4.6,
    reviews: 45,
    specs: ["IPS Touch Display", "Zigbee 3.0", "Voice Control", "Wall Mountable"]
  },
  {
    id: 14,
    name: "Aura Tablet Pro X",
    price: 849.00,
    originalPrice: 949.00,
    discount: 10,
    image: "/tablet_device_1776680751360.png",
    category: "Mobiles",
    description: "Power meets portability. Features an Ultra Retina OLED display and the latest performance chip for creators.",
    rating: 4.9,
    reviews: 210,
    specs: ["12.9\" OLED", "1TB Storage", "5G Connectivity", "Pro Stylus Support"]
  }
];

export const categories = [
  { id: '1', name: 'Mobiles', icon: '📱' },
  { id: '2', name: 'Computers', icon: '💻' },
  { id: '3', name: 'Audio', icon: '🎧' },
  { id: '4', name: 'Wearables', icon: '⌚' },
  { id: '5', name: 'Cameras', icon: '📷' },
  { id: '6', name: 'Accessories', icon: '⌨️' },
  { id: '7', name: 'Fashion', icon: '👗' },
  { id: '8', name: 'Grocery', icon: '🛒' },
  { id: '9', name: 'Stationery', icon: '🖊️' },
  { id: '11', name: 'Monitors', icon: '🖥️' },
];

